### ISSUE TITLE
Suggestion: let sampclass use selected column from the phenoData

### ISSUE THREAD

**Issue by jotsetung** [sneumann/xcms#17]
dear All,
I am not completely happy with the behavior of the xcmsSet sampclass method. I think it works nicely when a single column phenodata is provided or if the class labels are estimated from directories, but it's not really that intuitive for the way I'm used to work with phenodata objects (from microarray or RNA-seq experiments). Basically, my phenodata always have multiple columns describing each parameter specific for a file. So, I do also have sample grouping in the phenodata data.frame (usually a column names "class" or "group"), but the sampclass method does not honor that, it just returns a one class per sample.

My suggestion now would be to check in the sampclass method if the phenoData contains a column "class" and if present, return its content, otherwise do as it does now (i.e. interaction(object@phenoData)). Also, this would fit with the sampclass<- method, that actually replaces the content of a (existing or new) "class" column in the phenoData.

You think that might be OK? In case, I can then change the method and update the documentation.

cheers, jo

**Comment by sneumann** [comment]
Hi Jo, I have little exposure to microarray pd .
so: 1) single column phenoData -> no change 2) if pd[,"class"] exists, use that as sampClass() <-  
otherwise nteraction(object@phenoData)) (which is the same as 1) for single column pd).
It would be great if  `sampclass(xs) <- phenoData[,c("factor3", "factor7")]`would do what I expect,
i.e. allow easy re-configuration of the sampclasses which are used for e.g. group(minfrac=1).
Yours,
Steffen

**Comment by jotsetung** [comment]
you mean, for sampclass(xs) <- phenoData[, c("factor3", "factor7")] that sampclass would be the interaction of the two. that shouldn't be a problem.
jo

**Comment by sneumann** [comment]
Yes, excatly. Thx. Steffen

**Comment by jotsetung** [comment]
Done, it's now all included in my pull request.

bests, jo
