### ISSUE TITLE
Implement the lockMassFreq and stitch methods for OnDiskMSnExp

### ISSUE THREAD

**Issue by jorainer** [sneumann/xcms#177]
Implement methods to perform `stitch` etc for `OnDiskMSnExp` objects (see issue #173).

**Comment by maiyama** [comment]
Hello Johannes, 
Is there any update on this issue? 
My colleague and I are struggling with MS data (just MS1) from Waters with Lock Mass gaps. 
We have converted the RAW data into mzXML with lockmass refiner and filter to select only MS 1. In this way, the resulting data should contain only the sample data with gaps. We have tried older functions; xcmsSet with centWave method and lockMassFreq = TRUE but gaps were still found during the retention time correction step with retcor.obiwarp(). 
Below is the output of the retcor.obiwarp() for the first two files. In total I used 9 files. The time shown as gaps were the same for all 9 files. 

> rt_xdata <- retcor.obiwarp(grouped_xdata)
center sample:  7 
Processing: 1  Create profile matrix with method 'bin' and step 1 ... OK
Create profile matrix with method 'bin' and step 1 ... OK
Found gaps: cut scantime-vector at  103.671 seconds 
Found gaps: cut scantime-vector at  103.669 seconds 
2  Create profile matrix with method 'bin' and step 1 ... OK
Found gaps: cut scantime-vector at  103.671 seconds 
Found gaps: cut scantime-vector at  103.67 seconds 

We have also looked into the method mentioned in this paper (https://www.ncbi.nlm.nih.gov/pubmed/23615935) but the process requires Windows system and MassLynx software. We would like to have the whole workflow under Linux system without diverging into different environment or commercially licensed software. 

We will appreciate any comments on this. 
Thank you.

**Comment by jorainer** [comment]
No, haven't found the time to look into this. Also I had the impression that that was no longer a problem (see also issue #174).

**Comment by stanstrup** [comment]
In my hands it seems to work if you just remove the Lockmass scans. The refiner does not seem to be really needed with the data I tried. I had a conversation with one of the ProteoWizard guys that said it depended in the version of MassLynx used to record the files and even potentially what version was used to open (!!!) the files at some point (it might silently apply the correction).
So just get the functions/scansEvents you want and check a few scans to be sure the masses are correct. Then you should be good. Add something like this to the command:
```
--filter "scanEvent 1" --mzML --zlib --64
```

As for the `stitch` method: The implementation makes assumptions about the interscan times around a lockmass scan. With my data this assumption didn't hold and thus it never worked. So I would avoid using this at all and I think it is also time to drop it since the conversion should now work correctly.

**Comment by maiyama** [comment]
Johannes and Jan, thank you for the quick reply. 
I tried the filter below for msconvert on Docker; 
`-z --mzML --filter "peakPicking true 1-" --filter "scanEvent 1" --filter "msLevel 1" --filter "lockmassRefiner mz=556.277 tol=0.5"
`
I noticed that the numbers of ROI and peaks found were substantially larger (about double) than before during the peak picking step; however, the issue of gaps still seems to persist. Below is the output for one of the files. 

> Sample number 3 used as center sample.
> Aligning CQ06.mzML against CQ03.mzML ... Found gaps in scan times of the center sample: cut scantime-vector at NA seconds.
> Found gaps in scan time of file CQ06.mzML: cut scantime-vector at NA seconds.
> OK

This ends with the output saying "Applying retention time adjustment to the identified chromatographic peaks ... OK" but the RT correction plot shows up as just two horizontal lines.

Is there anything else I should try?

**Comment by maiyama** [comment]
I looked into what Johannes commented last year (https://github.com/sneumann/xcms/issues/248#issuecomment-363430108) and tried `adjustRtime-peakGroups` instead. 
It generated the output below and `plotAdjustedRtime(rt_xdata)` showed a plot with wavy lines instead of the straight horizontal lines. 

> Performing retention time correction using 2622 peak groups.
> Applying retention time adjustment to the identified chromatographic peaks ... OK

Seems like it worked this time!

**Comment by jorainer** [comment]
Good to hear that it worked @maiyama (at least with peak groups)!

I close this issue now (also because I don't think we will implement the mentioned functions anymore). Feel free to re-open if necessary.
