### ISSUE TITLE
Autofill the DoE for XCMSnExp object based on folder structure

### ISSUE THREAD

**Issue by yufree** [sneumann/xcms#195]
Hi, auto-determination of phenoData is a nice feature in `xcmsSet` object. How about wraping this function with `readMSData2` to make the user directly get a prepared objects? 

I write one as follows referring to the code in `xcmsSet`( only `data.frame` or `NAnnotatedDataFrame` class could be used for predefined phenoData and I directly use `phenoDataFromPaths` in this package) :

```
path2exp <- function(path,index = F,snames = NULL, sclass = NULL, phenoData = NULL){
        files <- list.files(path, recursive = TRUE,
                            full.names = TRUE)
        if (index) {
                files <- files[index]
        }
        
        fromPaths <- xcms:::phenoDataFromPaths(files)
        if (is.null(snames)) {
                snames <- rownames(fromPaths)
        } else {
                rownames(fromPaths) <- snames
        }
        
        if (is.null(snames)) {
                snames <- rownames(fromPaths)
        } else {
                rownames(fromPaths) <- snames
        }
        pdata <- phenoData
        if (is.null(pdata)) {
                pdata <- sclass
                if (is.null(pdata))
                        pdata <- new("NAnnotatedDataFrame", fromPaths)
        }else{
                if (class(pdata) == "data.frame")
                        pdata <- new("NAnnotatedDataFrame", fromPaths)
                if (class(pdata) != "NAnnotatedDataFrame")
                        stop("phenoData has to be a data.frame or NAnnotatedDataFrame!")
        }
        raw_data <- MSnbase::readMSData2(files, pdata = pdata)
        return(raw_data)
}
```
Also, I suggest adding this feature for `readMSData2`( for `MSnbase` package) if possible.

**Comment by jotsetung** [comment]
Thanks for the suggestion @yufree . I would however not include a function that infers phenodata from a folder structure into `readMSData2` since reading data and defining the experimental set-up/phenodata are separate things. Also, usually you want to describe the individual samples in much more detail than can be done by putting them into folders named according to the main sample groups.

I will look into this and try to come up with a solution. Exporting the `phenoDataFromPaths` would be the first step. Users that want to use the `xcmsSet`-style of just providing the path to the files could use then an approach like you described above.

**Comment by yufree** [comment]
Thanks @jotsetung ! `phenoDataFromPaths` is the key for this purpose.

**Comment by jotsetung** [comment]
It's exported in the current `devel` branch. to install use `devtools::install_github("sneumann/xcms")`.
