### ISSUE TITLE
Default group info for groupChromPeaks-density in xcms3

### ISSUE THREAD

**Issue by yufree** [sneumann/xcms#228]
Hi, I found the default sample group for groupChromPeaks-density is `numeric()`.  In xcmsset, such default value could be passed from `sampleclass`. This default setting is fine for samples from the same group. However, in most multigroup cases, the group information would influence the results by `minFraction = 0.5` and `minSamples = 1`. 

Could we set the default value as `xset@phenoData$class` in case most users only use the default setting(e.g. `PeakDensityParam()`)?

Thanks,

Miao

**Comment by jotsetung** [comment]
Thank you Miao for your suggestion.

I changed the default grouping as it was used in `group,xcmsSet` on purpose because:
1) Having the grouping factor called `$class` is misleading in the first place (at least I was used to use something like `sample_group` for that purpose).
2) Forcing the user to have the grouping variable in a a fixed-named `phenoData` column can be problematic. What if you define your grouping as e.g. $KO and have by chance a column $class in your phenoData? That would lead to unexpected results.

I thought it might be good to put more responsibility on the user and force him/her to define the settings explicitly.

Also, I strongly discourage users to use the default parameters. They work only on few examples. It is more important that users understand the impact of their settings.

In any rate, it is just a matter of calling `PeakDensityParam` with
```r
pdp <- PeakDensityParam(sampleGroups = xdata$class)  # If you use the *old* xcmsSet style
pdp <- PeakDensityParam(sampleGroups = xdata$sample_group)  # if the grouping is defined in another column
```

Now, what I could do is to require the `sampleGroups` argument to `PeakDensityParam` to be defined and throw an error if it is not passed to the `PeakDensityParam` constructor function. Would you be OK with that?

cheers, jo

**Comment by yufree** [comment]
Sounds good! An error is better for 'default' users.
Thanks,
Miao
