### ISSUE TITLE
Update parallel processing to BiocParallel

### ISSUE THREAD

**Issue by sneumann** [sneumann/xcms#27]
Hi,

xcms currently uses several packages (snow, rmpi) for parallel processing, 
and handles cluster setup and teardown manually. 

Enhancement: migrate both findPeaks() and fillPeaks() handling to biocParallel
https://bioconductor.org/packages/release/bioc/html/BiocParallel.html

Yours,
Steffen

**Comment by jotsetung** [comment]
Done that in https://github.com/sneumann/xcms/commit/55817bd32eb2bae345737d16a24883e527474347 . For now I've just added additional functions/methods instead of replacing the original ones. If you find that acceptable (RUnit test confirms results are identical) I could go forward replacing the original ones, deprecating the *old* code (e.g. obsolete `xcmsParallelSetup` etc) and updating the documentation.

**Comment by jotsetung** [comment]
Aah sorry; I pushed to the wrong remote, i.e. directly to the *devel* branch instead of the *devel* branch of my fork.

Since the changes I made (commit https://github.com/sneumann/xcms/commit/e81b590fd2596829103798e5d8b19e2fdfde2018) are mainly related to the parallel processing (i.e. use `BiocParallel` `bplapply` for parallel processing instead of the *old* code) there should be no big problem.

In addition I fixed some minor stuff in the *NAMESPACE* to reduce the warnings on package load.
I hope you find my changes acceptable. In future I will definitely avoid pushing directly to *devel*.

**Comment by jotsetung** [comment]
I think that issue can be closed; remains to bump the package version in *DESCRIPTION* and commit to Bioc svn.

**Comment by rietho** [comment]
To let you know: The manual of `fillPeaks` (xcms/man/fillPeaks.chrom-methods.Rd) does not show  `nSlaves` as deprecated yet.

**Comment by jotsetung** [comment]
Thanks for looking into that! I'll fix.
