### ISSUE TITLE
Reduce the number of methods

### ISSUE THREAD

**Issue by jotsetung** [sneumann/xcms#33]
Some of the methods should be changed to functions, such as
- [ ] `specDist...` methods.
- [ ] `group...` methods.
- [ ] `findPeaks...` methods.

This also facilitates documentation.
So in the end there will only be one e.g. `specDist` method that calls different functions based on the specified `method`.

**Comment by sneumann** [comment]
What could have been the reason we had them as methods initially ? 
I am not an expert in R language aesthetics. Would the choice change 
if other packages also had group() functions/methods ? What else 
influences the choice between function/method ? Happy to get just 
a pointer to relevant documents/best practice rather than you having 
to elaborate a long answer. Yours, Steffen

**Comment by jotsetung** [comment]
It relates a little to https://github.com/lgatto/MSnbase/issues/111 . 
Principally, methods only really make sense if they are implemented for at least two different objects; otherwise a function would suffice. Also, as you already mentioned, it makes sense when a generic is defined in another package.
I find also the documentation of functions easier to read (and to create) than for methods.

**Comment by sneumann** [comment]
So this is a no-brainer for specDist and findPeaks, but the name group() might be too 
generic to get away with a simple function. Can one easily check the expected fallout 
from changing group() ?

**Comment by jotsetung** [comment]
I think I was not clear here: I don't want to change `group` from a method to a function, but the downstream methods `group.density`, `group.nearest` etc. To the user this wouldn't change anything. 
So, the `group`, `findPeaks` and `specDist` will remain methods (also because in the long run they might be implemented also for `OnDiskMSnExp` objects in addition to the `xcmsRaw`).
