### ISSUE TITLE
Read Exported mgf files with "special fields"

### ISSUE THREAD

**Issue by michaelwitting** [sneumann/xcms#350]
I don't know if it fits here or in `MSnbase`, but can we read again the .mgf files with special fields we exported from a `Spectra` object back into a `Spectra` object with all its annotations?

Just had a problem like this and it would make life much easier, when working with annotated MS2 spectra for example, e.g. containing cluster ids etc...

**Comment by michaelwitting** [comment]
I just checked the code for `MSnbase`. I think I have an idea of how to come up with a solution. Might be not nice, but working for the beginning.

**Comment by jotsetung** [comment]
In principle I really like the idea - only, we are at present reorganizing things in `MSnbase` and that's why I'm a little hesitant to add new code to generate `Spectra` classes. In the end it could be that the `Spectra` class will be quite different than the present implementation (in fact a replacement of the `MSnExp`) that allows to use different backends (keep the data in-memory, read from mzML files, read/store in hdf5 files, database etc).

**Comment by michaelwitting** [comment]
No problem. I will implement the function in my `masstrixR` package then. I sought it might be interesting. I think it fits there, since I have already implemented a few functions for working with MS2 data.

**Comment by jorainer** [comment]
Think we can close this issue now. All should be available/fixed.
