### ISSUE TITLE
Unable to specify scanrange with xcms3

### ISSUE THREAD

**Issue by jsychong** [sneumann/xcms#351]
Hi,

I'm trying to specify the scanrange to be incorporated during the peak picking of the XCMSnExp. I've read through previous issues and found that this was fixed and available for xcmsraw, is there something like this for CentWaveParam/findChromPeaks?

Thanks!

**Comment by jotsetung** [comment]
Hi, 
the `scanrange` parameter is no longer supported in `xcms` version > 3 (it was also not implemented in a consistent way). What you can do now is to subset/filter your object before doing the peak detection. So, after reading the data with `data <- readMSData(... mode = "onDisk")` you can subset your `data` either with `filterRt` (filter by retention time) or `filterAcquisitionNum` (filter by the spectra's acquisition number within the mzML files). If possible I'd use `fiterRt` because it's easier, simply provide the lower and upper retention time to which you would like to subset your data. To subset to all spectra that are recorded from 2 to 250 seconds use `data <- filterRt(data, rt = c(2, 250))`.
For `filterAcquisitionNum` you have to provide the actual acquisition numbers. You can get them for each spectrum in your data with `acquisitionNum(data)`. To filter the data to contain only spectra with a scan/acquisition number from 2 to 200 from each file you would use `data <- filterAcquisitionNum(data, 1:200)`.

**Comment by jsychong** [comment]
Perfect, thanks so much for the help!
