### ISSUE TITLE
Running adjustRtime twice

### ISSUE THREAD

**Issue by stanstrup** [sneumann/xcms#382]
With the old interface it was possible to run retention time correction twice. I often did that to plot the deviation after the correction to check if the deviation decrease a lot or if the correction really was insignificant.

But now you cannot do that with `adjustRtime`.
The cause is that `adjustRtime` starts by `dropAdjustedRtime` which removes grouping too.
Is this intended behavior?

If so is there a way to get the `plotAdjustedRtime` output as if a second round of `adjustRtime` had been fitted?

**Comment by jorainer** [comment]
Well, yes, dropping previous alignment results was intentional. 

You however can run a second round of retention time correction after calling `applyAdjustedRtime`. This function replaces the raw retention times with the adjusted ones - in contrast to keeping the adjusted retention times along with the raw ones. You could do this repeatedly if you want several rounds of retention time adjustments - hope that helps with your problem.

**Comment by stanstrup** [comment]
Thanks! Did the trick.
