### ISSUE TITLE
groupChromPeaks giving error

### ISSUE THREAD

**Issue by joannawolthuis** [sneumann/xcms#416]
Hi there! I've done peak calling on a large number of samples, and would like to do peak grouping on them. I've mapped out which samples belong to which filenames (I have 3 technical replicates, in the end I'd like to average that signal too but that's a seperate issue). When I set the parameters for the mzClust peak grouping I get the following:

```
mzc_prm <- MzClustParam(ppm = 1,sampleGroups = samplegroups,minSamples = 2)
summed_grouped <- groupChromPeaks(res, param = mzc_prm)
8.03  14.06  17.07  55.25  Error in while (pos < numpeaks && p[pord[pos], 1] <= error_range[2]) { :
  missing value where TRUE/FALSE needed

```
where samplegroups has no missing values, and the res object (spectra with no peaks were not included so each of these has found peaks) looks like:

```
MSn experiment data ("XCMSnExp")
Object size in memory: 1.79 Mb
- - - Spectra data - - -
 MS level(s): 1
 Number of spectra: 210
 MSn retention times: 1:32 - 1:32 minutes
- - - Processing information - - -
Concatenated [Thu Oct  3 18:12:12 2019]
 MSnbase version: 2.10.1
- - - Meta data  - - -
phenoData
  rowNames: RES_20190821_001_neg.mzXML RES_20190821_002_neg.mzXML ...
    RES_20190821_269_neg.mzXML (210 total)
  varLabels: sampleNames
  varMetadata: labelDescription
Loaded from:
  [1] RES_20190821_001_neg.mzXML...  [210] RES_20190821_269_neg.mzXML
  Use 'fileNames(.)' to see all files.
protocolData: none
featureData
  featureNames: F1.S1 F2.S1 ... F210.S1 (210 total)
  fvarLabels: fileIdx spIdx ... spectrum (33 total)
  fvarMetadata: labelDescription
experimentData: use 'experimentData(object)'
- - - xcms preprocessing - - -
Chromatographic peak detection:
 method: MSW
 13337 peaks identified in 210 samples.
 On average 63.5 chromatographic peaks per sample.
```

Any idea of what could be going wrong? Thank you :)

**Comment by jorainer** [comment]
Could you eventually try also peak density grouping? just to see if it's an error related to your files/samples or the mzClust algorithm (actually never used that one myself).

**Comment by jorainer** [comment]
a sorry, was completely off - you have single spectra files, so not peak density possible. Would it be possible for you to share the `chromPeak` matrix? I could then have a look what actually happens (and goes wrong) within the `mzClust` function.

**Comment by joannawolthuis** [comment]
No worries, thanks for your quick reply :) How should I save the matrix, just do chromPeaks(res) and then save that result as RData? Or should I write to csv?

**Comment by joannawolthuis** [comment]
Just in case it was RData ;) Here you go:
[chrompeaks_debug.RData.zip](https://github.com/sneumann/xcms/files/3687301/chrompeaks_debug.RData.zip)

**Comment by joannawolthuis** [comment]
Hi Johannes! I don't mean to rush you, but as I kind of have a deadline next week I will also give it a shot   since it's the last step of the pipeline, if I solve it I will let you know :)

**Comment by jorainer** [comment]
Sorry for not replying for so long. Yes, if you solve it please let me know. I will also have a look at it, but external fixes are always highly welcome!

**Comment by jorainer** [comment]
I had a look and it seems the problem is that column `"mz"` contains some missing values. I added a fix that checks for this and, if it finds `NA`s but columns `"mzmin"` and `"mzmax"` are present (and have valid values) uses the mean of these as m/z.

If you're on Bioconductor 3.9 you can install the fix with `devtools::install_github("sneumann/xcms", ref = "RELEASE_3_9")`, if you're using the current developmental version with `devtools::install_github("sneumann/xcms", ref = "jomaster")`.

This *should* fix the issue - let me know if it doesn't.

**Comment by joannawolthuis** [comment]
Thanks so much!!! I found my old code back that was a bit easier to toy with and also saw the missing values deep in there :-) I'll update to the new branch and let you know - I'm a bit concerned why the missing values are there to begin with though, I hope there's not something wrong with my MSW peak calling settings 🤔

**Comment by jorainer** [comment]
I was also a little concerned with the `NA`s, but there's not much we can do in `xcms` because this calls directly code from the `MassSpecWavelet` package. I would suggest you to have a look a the raw data for some of the peaks with the `NA` `"mz"` to see if the detected peak still looks OKish.

**Comment by joannawolthuis** [comment]
This is ok to close, thank you :) I opened another issue on the NAs, potential way to stop them from happening, I hope...

**Comment by yuanman1011** [comment]
Hi，I want to group the peaks by using the mzClust algorithm.But I found some differences between the algorithm  introduced in reference and codes.And I want to ask some question：
1. Where is the “R_mzClust_hclust” ?
2. What is the “last cluster in C” ?
3.In the mz_clust codes, why is it “if(binclust != 1)” instead of “ if(binclust == 0)” ?[
![4500E484-5D36-4D27-8FC5-D1B705ADE25B](https://user-images.githubusercontent.com/55010832/97957986-3f34ae00-1de7-11eb-88a8-9e56ffa97ddc.jpeg)
![D2FAD649-D8D0-4CEC-9104-E0FBC61D485F](https://user-images.githubusercontent.com/55010832/97957988-422f9e80-1de7-11eb-9d2f-e366100eca2b.jpeg)
![E74F8802-D9DA-4C76-8B3E-47806650C8AE](https://user-images.githubusercontent.com/55010832/97957990-42c83500-1de7-11eb-82e0-4826f1eadfee.jpeg)


](url)

**Comment by yuan596** [comment]
Hi，I want to group the peaks by using the mzClust algorithm.But I found some differences between the algorithm  introduced in reference and codes.And I want to ask some question：
1. Where is the “R_mzClust_hclust” ?
2. What is the “last cluster in C” ?
3.In the mz_clust codes, why is it “if(binclust != 1)” instead of “ if(binclust == 0)” ?[
![4500E484-5D36-4D27-8FC5-D1B705ADE25B](https://user-images.githubusercontent.com/55010832/97957986-3f34ae00-1de7-11eb-88a8-9e56ffa97ddc.jpeg)
![D2FAD649-D8D0-4CEC-9104-E0FBC61D485F](https://user-images.githubusercontent.com/55010832/97957988-422f9e80-1de7-11eb-9d2f-e366100eca2b.jpeg)
![E74F8802-D9DA-4C76-8B3E-47806650C8AE](https://user-images.githubusercontent.com/55010832/97957990-42c83500-1de7-11eb-82e0-4826f1eadfee.jpeg)


](url)
