### ISSUE TITLE
1 parallel job did not deliver a result Error in result[[njob]] <- value :    attempt to select less than one element in OneIndex

### ISSUE THREAD

**Issue by AmbilySivadas** [sneumann/xcms#437]
Hi,

I am trying to run xcmsSet on RStudio (R 3.6.0) that is running on a linux server using the following command:

set <- xcmsSet(files, method = "centWave", BPPARAM = MulticoreParam(detectCores()-1, progressbar = TRUE))

But it errors out with the following message:

1 parallel job did not deliver a resultError in result[[njob]] <- value : 
  attempt to select less than one element in OneIndex

The error disappears when I use SerialParam(). But I want to utilize multiple cores.

Is this an R 3.6.0 problem?

Kindly guide.

**Comment by jorainer** [comment]
Dear @AmbilySivadas , have you tried to run the full processing using `SerialParam`? This would be important to see if you get an error in one of your files. The error message you get with parallel processing is just too cryptic to understand what actually failed.

**Comment by grangel0955** [comment]
I am also having trouble with the same error using R3.6.1 on a Linux Red Hat server when I try to run the "mz" or the "chromatogram" functions:

> mzs<-mz(raw_data)
Error in result[[njob]] <- value : 
  attempt to select less than one element in OneIndex

or 

> bpis <- chromatogram(raw_data, aggregationFun = "max")
Error in result[[njob]] <- value : 
  attempt to select less than one element in OneIndex

Interestingly, it only happens most of the time. Occasionally, I am able to run the functions and successfully get the desired objects back without error. I initially thought I had success because I began requesting multiple cores for processing, but I have since tried again, using the same script and am now getting the error even with multiple cores. 

Have you found any solution, Ambily?

**Comment by jorainer** [comment]
I experienced the same error on a very large data set when I ran out of memory (although the error message seems to be unrelated to memory). Thus my suggestion to disable parallel processing with `register(SerialParam())` before the call (or passing `BPPARAM = SerialParam()` to the function). 

Also, have an eye at the memory consumption, it's amazing how large MS datasets can be. Thus I usually don't run the code on too many cores because a) memory demand can be very large and b) i/o can become a bottleneck (since each parallel process starts reading data from the raw files).

**Comment by jorainer** [comment]
Closing the issue now. Feel free to re-open if needed.

**Comment by michael-swift** [comment]
just coming by to say for folks get here via google by searching variants of this error message: I got the same error running a different program in R and it was an oom-kill issue

**Comment by sneumann** [comment]
Thanks for reporting back ! Here is a link on finding more about the OOM event: https://www.baeldung.com/linux/which-process-killed Maybe that is also relevant for @AharoniLab ? Yours, Steffen
