### ISSUE TITLE
Is the ppm parameter in Centwave both sides or single side?

### ISSUE THREAD

**Issue by amnahsiddiqa** [sneumann/xcms#609]
Hi Johannes,

From the tutorial on analysis of XCMS (https://bioconductor.org/packages/devel/bioc/vignettes/xcms/inst/doc/xcms.html#3_Initial_data_inspection- Please see attached screenshot for exact text) my impression is that the ppm parameter in centWave is both sides from mean; Could you please verify that for me ; So to say if 5 ppm is user defined ppm - the total difference in a max and min centroids in an ROI could be 10 ppm?

![Screen Shot 2022-04-07 at 12 30 06 PM](https://user-images.githubusercontent.com/28387956/162252312-5dfc6572-b483-45b2-bafe-a32d4f7cc940.png)

Thanks,
Amnah

**Comment by stanstrup** [comment]
Your interpretation matches my memory and what I understood from the code checking it now.

**Comment by jorainer** [comment]
Looking a the code (not that easy because it's C code and also not mine):

for each new scan:
- calculate the absolute difference between the mean m/z of the ROI and the m/z of the current scan
- if that absolute difference is < ppm * m/z of current scan:
  - merge the current scan into the ROI and update the mean m/z of the ROI
- other wise start a new ROI

so, I can confirm what Jan wrote, due to the `abs` it can be that the m/z difference between individual scans is > ppm. It is hard to say if the max is exactly 2 * ppm, because the comparison is always done against the mean m/z of all data points within the ROI.

**Comment by amnahsiddiqa** [comment]
Thank you very much both of you. This was very helpful and I am clear on this now.
