### ISSUE TITLE
Suggest for featureValues()

### ISSUE THREAD

**Issue by DrRuiLi** [sneumann/xcms#628]
The default column names in output of featureValues() were fileNames(XCMSnExp) and no other options, should there be other options such as sampleNames(XCMSnExp) or customized vector?
![image](https://user-images.githubusercontent.com/69882346/181739969-94dbc266-bf5a-4b4d-8223-2207fd138cd7.png)

**Comment by jorainer** [comment]
Thanks for the suggestion - but I would rather keep it with file names, as *sample* names are not mandatory and we can not expect that users provide this information at all (or know in which column this information is provided).

Ideally, I would anyway suggest to use the `quantify` method from `xcms` that returns a standard Bioconductor `SummarizedExperiment` object with the feature values as *assay* data. All additional sample annotations are also provided and stored in the object's `colData` slot and can in addition be accessed with `$`. Since the `colData` needs to have the same order than the columns in `assay` (or `featureValues`) it is quite easy to get additional annotations for each column in the feature abundance matrix.
