### ISSUE TITLE
Preprocessing MS2 DDA data

### ISSUE THREAD

**Issue by MuyaoXi9271** [sneumann/xcms#632]
Hi expert,

I have learned the examples of how to preprocess DDA data (https://bioconductor.org/packages/release/bioc/vignettes/xcms/inst/doc/xcms-lcms-ms.html#2_Analysis_of_DDA_data and https://bioconductor.org/packages/release/bioc/vignettes/xcms/inst/doc/xcms.html) and then upload results on the GNPS platform and run successfully 

Regarding both examples, I realize that peak picking is only done on MS1-level DDA data by the function “findChromPeaks”. Peak picking is not done on MS2-level DDA data? Is it because it is not necessary or simplifying the example?

I am looking forward to receiving any replies.

Bests,
Muyao

**Comment by jorainer** [comment]
AFAIK for DDA data there is not chromatographic peak detection on MS2 data needed. You do the MS1 chromatographic peak detection to quantify your metabolites and then get all MS2 spectra representing the fragment spectra for the ions of the detected chromatographic peak. These can then help to actually identify the metabolite you just quantified.

Note that I on purpose used the term *chromatographic peak detection* instead of *peak picking* because the latter can also mean peak detection along the m/z axis, i.e. within a single spectrum, while on MS1 data we usually analyze the data along the RT dimension to identify *chromatographic peaks* (in contrast to mass peaks).
