### ISSUE TITLE
msn2xcmsRaw needs deepCopy

### ISSUE THREAD

**Issue by stanstrup** [sneumann/xcms#76]
In msn2xcmsRaw  the @ env slot is changed. Even if a copy is made in the first line of the function (`x <- xmsn`) the "real data" is the same env so you also change the input object. At least that is my understanding.

so:

```r
x <- xmsn
```

should be:
```r
x <- deepCopy(xmsn)
```

This causes a real headache if you need the original and the changed object since the data in the env have now been changed for both objects but the non-env slots in the original xcmsRaw is still the same. So your input xcmsRaw is now non-sense :(

**Comment by sneumann** [comment]
Hi,  Thanks for the suggested fix. Will do. Yours Steffen

---
I blame Android for the brevity and typos


---- Jan Stanstrup schrieb ----


In msn2xcmsRaw the @ env slot is changed. Even if a copy is made in the first line of the function (x <- xmsn) the "real data" is the same env so you also change the input object. At least that is my understanding.

so:

x <- xmsn

should be:

x <- deepCopy(xmsn)

This causes a real headache if you need the original and the changed object since the data in the env have now been changed for both objects but the non-env slots in the original xcmsRaw is still the same. So your input xcmsRaw is now non-sense :(

**Comment by sneumann** [comment]
Merged Fix. Thanks Jan!
